package elcolegainformatico.antonio.puertoapp.Activities;

import android.content.Intent;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ListView;
import java.util.ArrayList;

import elcolegainformatico.antonio.puertoapp.Model.Articulo;
import elcolegainformatico.antonio.puertoapp.R;

/**
 * Created by antonio on 7/4/17.
 */

public class ArticulosListActivity extends AppCompatActivity {

    ListView listArticulos;
    ArrayList<Articulo> articuloArrayList;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        setTitle("Lista de articulos");

        setContentView(R.layout.activity_articulos_list); //le asigno su layout
        listArticulos=(ListView) findViewById(R.id.articulos_list); //Busco mi listView activity_articulos_list

        //Meto a manubrio los articulos
        loadArticulos();

        ArticulosAdapter myAdaptater = new ArticulosAdapter(articuloArrayList,ArticulosListActivity.this.getApplicationContext());
        listArticulos.setAdapter(myAdaptater);

        //Cuando seleccione algún item de la lista
        listArticulos.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {

                Articulo mArticulo = articuloArrayList.get(position);

                Intent intent = new Intent(ArticulosListActivity.this, ArticuloEditActivity.class);

                intent.putExtra("myArticulo", mArticulo); //Pasamos un objeto articulo Parcelable

                startActivity(intent);
            }

        });
    }

    public void loadArticulos(){

        articuloArrayList = new ArrayList<Articulo>();

        articuloArrayList.add(new Articulo("Articulo 1", "FUNDAMENTO LEGAL", "Este Reglamento cumplimenta y desarrolla lo dispuesto en los Artículos 31 de la Ley de Puertos de 19 de Enero de 1928 y 63 del Reglamento para su ejecución, en la Ley 27/1968 de 20 de junio, sobre Junta de Puertos y Estatuto de Autonomía , demás disposiciones concordantes con esta Ley y Decreto 2358/1975 de 11 de septiembre sobre sanciones en materia portuaria."));
        articuloArrayList.add(new Articulo("Articulo 13","VEHÍCULOS INDUSTRIALES Y MAQUINARIA","El acceso de vehículos industriales y de maquinaria móvil , se autorizará en cada caso por la Dirección del Puerto , que podrá controlar sus características y estado de conservación y funcionamiento de acuerdo con lo que se establece en este Reglamento, sin que por ello pueda derivarse ninguna responsabilidad para la Junta del Puerto ni para su personal , en caso de accidente."));
        articuloArrayList.add(new Articulo("Artículo 28","ENMENDADAS","Se procurará que los buques no tengan que cambiar de muelle ni enmendarse dentro de un mismo muelle , pero la Dirección del Puerto se reserva el derecho de disponer tales maniobras si las considera necesarias para la buena explotación del Puerto en su conjunto, sin que los representantes del buque puedan presentar reclamación alguna por perjuicios o gastos ocasionados.\n" + "Las variaciones de atraque estarán específicamente indicadas cuando por falta del espacio u otra causa se designe para un buque atraque diferente al que corresponde para las operaciones que debe realizar, y cuando se condicione el atraque por los servicios de la Junta del Puerto al hacer su designación ."));
        articuloArrayList.add(new Articulo("Artículo 66","NORMAS GENERALES","Se tomarán todas las medidas precisas para no ocasionar daños o sustracciones en las obras , instalaciones , equipos, útiles, efectos, materiales o mercancías existentes en la zona portuaria." + "Cuando se produzcan daños a las obras, utillaje o instalaciones del Puerto, la Junta del Puerto, tendrá derecho a resarcirse de los gastos que origine la reparación y al demérito que sufra el bien dañado, así como de los perjuicios ocasionados"));
        articuloArrayList.add(new Articulo("Artículo 65","PROHIBICIONES GENERALES","Quedan prohibidas terminantemente todas las acciones contrarias a la moral , decencia , salubridad o higiene pública o al respeto debido a las personas , en especial a los Celadores Guarda muelles y demás agentes de la Autoridad , los comportamientos groseros , escandalosos o agresivos , la mendicidad o vagancia y , en general , los actos que perturben la buena marcha de los servicios del Puerto , o la circulación dentro del mismo y cuanto constituya falta a las prescripciones de este Reglamento y órdenes complementarias dictadas por la Dirección del Puerto."));

        articuloArrayList.add(new Articulo("Articulo 1", "FUNDAMENTO LEGAL", "Este Reglamento cumplimenta y desarrolla lo dispuesto en los Artículos 31 de la Ley de Puertos de 19 de Enero de 1928 y 63 del Reglamento para su ejecución, en la Ley 27/1968 de 20 de junio, sobre Junta de Puertos y Estatuto de Autonomía , demás disposiciones concordantes con esta Ley y Decreto 2358/1975 de 11 de septiembre sobre sanciones en materia portuaria."));
        articuloArrayList.add(new Articulo("Articulo 13","VEHÍCULOS INDUSTRIALES Y MAQUINARIA","El acceso de vehículos industriales y de maquinaria móvil , se autorizará en cada caso por la Dirección del Puerto , que podrá controlar sus características y estado de conservación y funcionamiento de acuerdo con lo que se establece en este Reglamento, sin que por ello pueda derivarse ninguna responsabilidad para la Junta del Puerto ni para su personal , en caso de accidente."));
        articuloArrayList.add(new Articulo("Artículo 28","ENMENDADAS","Se procurará que los buques no tengan que cambiar de muelle ni enmendarse dentro de un mismo muelle , pero la Dirección del Puerto se reserva el derecho de disponer tales maniobras si las considera necesarias para la buena explotación del Puerto en su conjunto, sin que los representantes del buque puedan presentar reclamación alguna por perjuicios o gastos ocasionados.\n" + "Las variaciones de atraque estarán específicamente indicadas cuando por falta del espacio u otra causa se designe para un buque atraque diferente al que corresponde para las operaciones que debe realizar, y cuando se condicione el atraque por los servicios de la Junta del Puerto al hacer su designación ."));
        articuloArrayList.add(new Articulo("Artículo 66","NORMAS GENERALES","Se tomarán todas las medidas precisas para no ocasionar daños o sustracciones en las obras , instalaciones , equipos, útiles, efectos, materiales o mercancías existentes en la zona portuaria." + "Cuando se produzcan daños a las obras, utillaje o instalaciones del Puerto, la Junta del Puerto, tendrá derecho a resarcirse de los gastos que origine la reparación y al demérito que sufra el bien dañado, así como de los perjuicios ocasionados"));
        articuloArrayList.add(new Articulo("Artículo 65","PROHIBICIONES GENERALES","Quedan prohibidas terminantemente todas las acciones contrarias a la moral , decencia , salubridad o higiene pública o al respeto debido a las personas , en especial a los Celadores Guarda muelles y demás agentes de la Autoridad , los comportamientos groseros , escandalosos o agresivos , la mendicidad o vagancia y , en general , los actos que perturben la buena marcha de los servicios del Puerto , o la circulación dentro del mismo y cuanto constituya falta a las prescripciones de este Reglamento y órdenes complementarias dictadas por la Dirección del Puerto."));

        articuloArrayList.add(new Articulo("Articulo 1", "FUNDAMENTO LEGAL", "Este Reglamento cumplimenta y desarrolla lo dispuesto en los Artículos 31 de la Ley de Puertos de 19 de Enero de 1928 y 63 del Reglamento para su ejecución, en la Ley 27/1968 de 20 de junio, sobre Junta de Puertos y Estatuto de Autonomía , demás disposiciones concordantes con esta Ley y Decreto 2358/1975 de 11 de septiembre sobre sanciones en materia portuaria."));
        articuloArrayList.add(new Articulo("Articulo 13","VEHÍCULOS INDUSTRIALES Y MAQUINARIA","El acceso de vehículos industriales y de maquinaria móvil , se autorizará en cada caso por la Dirección del Puerto , que podrá controlar sus características y estado de conservación y funcionamiento de acuerdo con lo que se establece en este Reglamento, sin que por ello pueda derivarse ninguna responsabilidad para la Junta del Puerto ni para su personal , en caso de accidente."));
        articuloArrayList.add(new Articulo("Artículo 28","ENMENDADAS","Se procurará que los buques no tengan que cambiar de muelle ni enmendarse dentro de un mismo muelle , pero la Dirección del Puerto se reserva el derecho de disponer tales maniobras si las considera necesarias para la buena explotación del Puerto en su conjunto, sin que los representantes del buque puedan presentar reclamación alguna por perjuicios o gastos ocasionados.\n" + "Las variaciones de atraque estarán específicamente indicadas cuando por falta del espacio u otra causa se designe para un buque atraque diferente al que corresponde para las operaciones que debe realizar, y cuando se condicione el atraque por los servicios de la Junta del Puerto al hacer su designación ."));
        articuloArrayList.add(new Articulo("Artículo 66","NORMAS GENERALES","Se tomarán todas las medidas precisas para no ocasionar daños o sustracciones en las obras , instalaciones , equipos, útiles, efectos, materiales o mercancías existentes en la zona portuaria." + "Cuando se produzcan daños a las obras, utillaje o instalaciones del Puerto, la Junta del Puerto, tendrá derecho a resarcirse de los gastos que origine la reparación y al demérito que sufra el bien dañado, así como de los perjuicios ocasionados"));
        articuloArrayList.add(new Articulo("Artículo 65","PROHIBICIONES GENERALES","Quedan prohibidas terminantemente todas las acciones contrarias a la moral , decencia , salubridad o higiene pública o al respeto debido a las personas , en especial a los Celadores Guarda muelles y demás agentes de la Autoridad , los comportamientos groseros , escandalosos o agresivos , la mendicidad o vagancia y , en general , los actos que perturben la buena marcha de los servicios del Puerto , o la circulación dentro del mismo y cuanto constituya falta a las prescripciones de este Reglamento y órdenes complementarias dictadas por la Dirección del Puerto."));

        articuloArrayList.add(new Articulo("Articulo 1", "FUNDAMENTO LEGAL", "Este Reglamento cumplimenta y desarrolla lo dispuesto en los Artículos 31 de la Ley de Puertos de 19 de Enero de 1928 y 63 del Reglamento para su ejecución, en la Ley 27/1968 de 20 de junio, sobre Junta de Puertos y Estatuto de Autonomía , demás disposiciones concordantes con esta Ley y Decreto 2358/1975 de 11 de septiembre sobre sanciones en materia portuaria."));
        articuloArrayList.add(new Articulo("Articulo 13","VEHÍCULOS INDUSTRIALES Y MAQUINARIA","El acceso de vehículos industriales y de maquinaria móvil , se autorizará en cada caso por la Dirección del Puerto , que podrá controlar sus características y estado de conservación y funcionamiento de acuerdo con lo que se establece en este Reglamento, sin que por ello pueda derivarse ninguna responsabilidad para la Junta del Puerto ni para su personal , en caso de accidente."));
        articuloArrayList.add(new Articulo("Artículo 28","ENMENDADAS","Se procurará que los buques no tengan que cambiar de muelle ni enmendarse dentro de un mismo muelle , pero la Dirección del Puerto se reserva el derecho de disponer tales maniobras si las considera necesarias para la buena explotación del Puerto en su conjunto, sin que los representantes del buque puedan presentar reclamación alguna por perjuicios o gastos ocasionados.\n" + "Las variaciones de atraque estarán específicamente indicadas cuando por falta del espacio u otra causa se designe para un buque atraque diferente al que corresponde para las operaciones que debe realizar, y cuando se condicione el atraque por los servicios de la Junta del Puerto al hacer su designación ."));
        articuloArrayList.add(new Articulo("Artículo 66","NORMAS GENERALES","Se tomarán todas las medidas precisas para no ocasionar daños o sustracciones en las obras , instalaciones , equipos, útiles, efectos, materiales o mercancías existentes en la zona portuaria." + "Cuando se produzcan daños a las obras, utillaje o instalaciones del Puerto, la Junta del Puerto, tendrá derecho a resarcirse de los gastos que origine la reparación y al demérito que sufra el bien dañado, así como de los perjuicios ocasionados"));
        articuloArrayList.add(new Articulo("Artículo 65","PROHIBICIONES GENERALES","Quedan prohibidas terminantemente todas las acciones contrarias a la moral , decencia , salubridad o higiene pública o al respeto debido a las personas , en especial a los Celadores Guarda muelles y demás agentes de la Autoridad , los comportamientos groseros , escandalosos o agresivos , la mendicidad o vagancia y , en general , los actos que perturben la buena marcha de los servicios del Puerto , o la circulación dentro del mismo y cuanto constituya falta a las prescripciones de este Reglamento y órdenes complementarias dictadas por la Dirección del Puerto."));

        articuloArrayList.add(new Articulo("Articulo 1", "FUNDAMENTO LEGAL", "Este Reglamento cumplimenta y desarrolla lo dispuesto en los Artículos 31 de la Ley de Puertos de 19 de Enero de 1928 y 63 del Reglamento para su ejecución, en la Ley 27/1968 de 20 de junio, sobre Junta de Puertos y Estatuto de Autonomía , demás disposiciones concordantes con esta Ley y Decreto 2358/1975 de 11 de septiembre sobre sanciones en materia portuaria."));
        articuloArrayList.add(new Articulo("Articulo 13","VEHÍCULOS INDUSTRIALES Y MAQUINARIA","El acceso de vehículos industriales y de maquinaria móvil , se autorizará en cada caso por la Dirección del Puerto , que podrá controlar sus características y estado de conservación y funcionamiento de acuerdo con lo que se establece en este Reglamento, sin que por ello pueda derivarse ninguna responsabilidad para la Junta del Puerto ni para su personal , en caso de accidente."));
        articuloArrayList.add(new Articulo("Artículo 28","ENMENDADAS","Se procurará que los buques no tengan que cambiar de muelle ni enmendarse dentro de un mismo muelle , pero la Dirección del Puerto se reserva el derecho de disponer tales maniobras si las considera necesarias para la buena explotación del Puerto en su conjunto, sin que los representantes del buque puedan presentar reclamación alguna por perjuicios o gastos ocasionados.\n" + "Las variaciones de atraque estarán específicamente indicadas cuando por falta del espacio u otra causa se designe para un buque atraque diferente al que corresponde para las operaciones que debe realizar, y cuando se condicione el atraque por los servicios de la Junta del Puerto al hacer su designación ."));
        articuloArrayList.add(new Articulo("Artículo 66","NORMAS GENERALES","Se tomarán todas las medidas precisas para no ocasionar daños o sustracciones en las obras , instalaciones , equipos, útiles, efectos, materiales o mercancías existentes en la zona portuaria." + "Cuando se produzcan daños a las obras, utillaje o instalaciones del Puerto, la Junta del Puerto, tendrá derecho a resarcirse de los gastos que origine la reparación y al demérito que sufra el bien dañado, así como de los perjuicios ocasionados"));
        articuloArrayList.add(new Articulo("Artículo 65","PROHIBICIONES GENERALES","Quedan prohibidas terminantemente todas las acciones contrarias a la moral , decencia , salubridad o higiene pública o al respeto debido a las personas , en especial a los Celadores Guarda muelles y demás agentes de la Autoridad , los comportamientos groseros , escandalosos o agresivos , la mendicidad o vagancia y , en general , los actos que perturben la buena marcha de los servicios del Puerto , o la circulación dentro del mismo y cuanto constituya falta a las prescripciones de este Reglamento y órdenes complementarias dictadas por la Dirección del Puerto."));

        articuloArrayList.add(new Articulo("Articulo 1", "FUNDAMENTO LEGAL", "Este Reglamento cumplimenta y desarrolla lo dispuesto en los Artículos 31 de la Ley de Puertos de 19 de Enero de 1928 y 63 del Reglamento para su ejecución, en la Ley 27/1968 de 20 de junio, sobre Junta de Puertos y Estatuto de Autonomía , demás disposiciones concordantes con esta Ley y Decreto 2358/1975 de 11 de septiembre sobre sanciones en materia portuaria."));
        articuloArrayList.add(new Articulo("Articulo 13","VEHÍCULOS INDUSTRIALES Y MAQUINARIA","El acceso de vehículos industriales y de maquinaria móvil , se autorizará en cada caso por la Dirección del Puerto , que podrá controlar sus características y estado de conservación y funcionamiento de acuerdo con lo que se establece en este Reglamento, sin que por ello pueda derivarse ninguna responsabilidad para la Junta del Puerto ni para su personal , en caso de accidente."));
        articuloArrayList.add(new Articulo("Artículo 28","ENMENDADAS","Se procurará que los buques no tengan que cambiar de muelle ni enmendarse dentro de un mismo muelle , pero la Dirección del Puerto se reserva el derecho de disponer tales maniobras si las considera necesarias para la buena explotación del Puerto en su conjunto, sin que los representantes del buque puedan presentar reclamación alguna por perjuicios o gastos ocasionados.\n" + "Las variaciones de atraque estarán específicamente indicadas cuando por falta del espacio u otra causa se designe para un buque atraque diferente al que corresponde para las operaciones que debe realizar, y cuando se condicione el atraque por los servicios de la Junta del Puerto al hacer su designación ."));
        articuloArrayList.add(new Articulo("Artículo 66","NORMAS GENERALES","Se tomarán todas las medidas precisas para no ocasionar daños o sustracciones en las obras , instalaciones , equipos, útiles, efectos, materiales o mercancías existentes en la zona portuaria." + "Cuando se produzcan daños a las obras, utillaje o instalaciones del Puerto, la Junta del Puerto, tendrá derecho a resarcirse de los gastos que origine la reparación y al demérito que sufra el bien dañado, así como de los perjuicios ocasionados"));
        articuloArrayList.add(new Articulo("Artículo 65","PROHIBICIONES GENERALES","Quedan prohibidas terminantemente todas las acciones contrarias a la moral , decencia , salubridad o higiene pública o al respeto debido a las personas , en especial a los Celadores Guarda muelles y demás agentes de la Autoridad , los comportamientos groseros , escandalosos o agresivos , la mendicidad o vagancia y , en general , los actos que perturben la buena marcha de los servicios del Puerto , o la circulación dentro del mismo y cuanto constituya falta a las prescripciones de este Reglamento y órdenes complementarias dictadas por la Dirección del Puerto."));

        articuloArrayList.add(new Articulo("Articulo 1", "FUNDAMENTO LEGAL", "Este Reglamento cumplimenta y desarrolla lo dispuesto en los Artículos 31 de la Ley de Puertos de 19 de Enero de 1928 y 63 del Reglamento para su ejecución, en la Ley 27/1968 de 20 de junio, sobre Junta de Puertos y Estatuto de Autonomía , demás disposiciones concordantes con esta Ley y Decreto 2358/1975 de 11 de septiembre sobre sanciones en materia portuaria."));
        articuloArrayList.add(new Articulo("Articulo 13","VEHÍCULOS INDUSTRIALES Y MAQUINARIA","El acceso de vehículos industriales y de maquinaria móvil , se autorizará en cada caso por la Dirección del Puerto , que podrá controlar sus características y estado de conservación y funcionamiento de acuerdo con lo que se establece en este Reglamento, sin que por ello pueda derivarse ninguna responsabilidad para la Junta del Puerto ni para su personal , en caso de accidente."));
        articuloArrayList.add(new Articulo("Artículo 28","ENMENDADAS","Se procurará que los buques no tengan que cambiar de muelle ni enmendarse dentro de un mismo muelle , pero la Dirección del Puerto se reserva el derecho de disponer tales maniobras si las considera necesarias para la buena explotación del Puerto en su conjunto, sin que los representantes del buque puedan presentar reclamación alguna por perjuicios o gastos ocasionados.\n" + "Las variaciones de atraque estarán específicamente indicadas cuando por falta del espacio u otra causa se designe para un buque atraque diferente al que corresponde para las operaciones que debe realizar, y cuando se condicione el atraque por los servicios de la Junta del Puerto al hacer su designación ."));
        articuloArrayList.add(new Articulo("Artículo 66","NORMAS GENERALES","Se tomarán todas las medidas precisas para no ocasionar daños o sustracciones en las obras , instalaciones , equipos, útiles, efectos, materiales o mercancías existentes en la zona portuaria." + "Cuando se produzcan daños a las obras, utillaje o instalaciones del Puerto, la Junta del Puerto, tendrá derecho a resarcirse de los gastos que origine la reparación y al demérito que sufra el bien dañado, así como de los perjuicios ocasionados"));
        articuloArrayList.add(new Articulo("Artículo 65","PROHIBICIONES GENERALES","Quedan prohibidas terminantemente todas las acciones contrarias a la moral , decencia , salubridad o higiene pública o al respeto debido a las personas , en especial a los Celadores Guarda muelles y demás agentes de la Autoridad , los comportamientos groseros , escandalosos o agresivos , la mendicidad o vagancia y , en general , los actos que perturben la buena marcha de los servicios del Puerto , o la circulación dentro del mismo y cuanto constituya falta a las prescripciones de este Reglamento y órdenes complementarias dictadas por la Dirección del Puerto."));


    }
}
